/**
 * Generates clean formatted Markdown report from document analysis.
 */
export function generateMarkdownReport(analysis) {
  if (!analysis) return '';

  const { metadata, sections, risks, checklist, disclaimer } = analysis;
  const now = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let md = `# Legal Document Analysis Report: ${metadata.filename || 'Contract'}\n`;
  md += `*Generated by ClarifyLaw AI on ${now}*\n\n`;
  md += `> **DISCLAIMER**: ${disclaimer}\n\n`;
  md += `---\n\n`;

  md += `## 1. Executive Summary\n`;
  md += `- **Document Type**: ${metadata.file_type}\n`;
  md += `- **Overall Assessed Risk**: ${metadata.overall_risk_score}\n`;
  md += `- **Length**: ${metadata.word_count} words (${metadata.section_count} sections)\n\n`;
  md += `${metadata.executive_summary}\n\n`;
  md += `---\n\n`;

  md += `## 2. Risk & Clause Radar (${risks.length} Flagged Terms)\n\n`;
  if (risks.length === 0) {
    md += `*No major high-risk clauses detected.*\n\n`;
  } else {
    risks.forEach((r, idx) => {
      const badge = r.severity === 'HIGH' ? '🔴 HIGH' : r.severity === 'MEDIUM' ? '🟠 MEDIUM' : '🔵 LOW';
      md += `### ${idx + 1}. [${badge}] ${r.clause_name}\n`;
      md += `- **Section**: ${r.section_id}\n`;
      md += `- **Why It Matters**: ${r.why_it_matters}\n`;
      md += `- **Potential Impact**: ${r.potential_impact}\n`;
      md += `- **Suggested Counter-Action**: ${r.suggested_action}\n`;
      md += `- **Contract Quote**: *"${r.original_quote.trim()}"*\n\n`;
    });
  }
  md += `---\n\n`;

  md += `## 3. Action Checklist & Next Steps\n\n`;
  md += `### ❓ Questions to Ask an Attorney\n`;
  checklist.questions_for_lawyer.forEach((q, i) => {
    md += `${i + 1}. [ ] ${q}\n`;
  });
  md += `\n### 🚩 Red Flags to Clarify Before Signing\n`;
  checklist.red_flags_to_clarify.forEach((rf, i) => {
    md += `${i + 1}. [ ] ${rf}\n`;
  });
  md += `\n### 📋 Recommended Next Steps\n`;
  checklist.recommended_next_steps.forEach((s, i) => {
    md += `${i + 1}. [ ] ${s}\n`;
  });
  md += `\n---\n\n`;

  md += `## 4. Plain-English Section-by-Section Simplification\n\n`;
  sections.forEach((sec) => {
    md += `### ${sec.title} (${sec.id})\n`;
    md += `**Category**: ${sec.category}\n\n`;
    md += `**Plain-English Meaning**:\n${sec.plain_english}\n\n`;
    if (sec.key_takeaways && sec.key_takeaways.length > 0) {
      md += `**Key Takeaways**:\n`;
      sec.key_takeaways.forEach((t) => {
        md += `- ${t}\n`;
      });
      md += `\n`;
    }
    md += `<details><summary>Original Text</summary>\n\n> ${sec.original_text.replace(/\n/g, '\n> ')}\n\n</details>\n\n`;
  });

  return md;
}

export function copyToClipboard(text) {
  return navigator.clipboard.writeText(text);
}

export function downloadMarkdown(content, filename = 'clarifylaw_analysis.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printReport() {
  window.print();
}
